table dim_customers
	lineageTag: 100de76f-949d-4560-bed3-3691ef7945e3

	column Customer_ID
		dataType: string
		lineageTag: 7463272b-c3c4-414a-9f76-beccf2781989
		summarizeBy: none
		sourceColumn: Customer_ID

		annotation SummarizationSetBy = Automatic

	column Customer_Name
		dataType: string
		lineageTag: b5ba1f89-acd1-4f19-b14d-d5195ff7f92a
		summarizeBy: none
		sourceColumn: Customer_Name

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: cd731e80-6f2a-4ea8-a337-f29a88c128e3
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Email
		dataType: string
		lineageTag: cc1a764e-4957-468c-b3e5-0b0c1e325b46
		summarizeBy: none
		sourceColumn: Email

		annotation SummarizationSetBy = Automatic

	column Join_Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 34572128-100d-4916-851b-2280d2cbeffd
		summarizeBy: none
		sourceColumn: Join_Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Loyalty_Level
		dataType: string
		lineageTag: b8db5127-cf06-4eb4-924d-590afe6469f7
		summarizeBy: none
		sourceColumn: Loyalty_Level

		annotation SummarizationSetBy = Automatic

	column 'Join_Year '
		dataType: int64
		formatString: 0
		lineageTag: 7cfd52da-c24c-4548-9168-4135452fb3f4
		summarizeBy: none
		sourceColumn: "Join_Year "

		annotation SummarizationSetBy = Automatic

	column Loyalty_Score
		dataType: string
		lineageTag: a4820ace-4ca1-4c27-845d-0ba536a90594
		summarizeBy: none
		sourceColumn: Loyalty_Score

		annotation SummarizationSetBy = Automatic

	partition dim_customers = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\anike\Documents\GitHub\Data Sets\Chocolate Sales Report\dim_customers.csv"),[Delimiter=",", Columns=6, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Customer_ID", type text}, {"Customer_Name", type text}, {"Segment", type text}, {"Email", type text}, {"Join_Date", type date}, {"Loyalty_Level", type text}}),
				    #"Split Column by Delimiter" = Table.SplitColumn(#"Changed Type", "Customer_Name", Splitter.SplitTextByEachDelimiter({" "}, QuoteStyle.Csv, false), {"Customer_Name.1", "Customer_Name.2"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"Customer_Name.1", type text}, {"Customer_Name.2", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type1",{{"Customer_Name.1", "First_Name"}, {"Customer_Name.2", "Last_Name"}}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Renamed Columns",{{"Join_Date", type date}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type2", "Join_Year ", each Date.Year([Join_Date])),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Added Custom",{{"Join_Year ", Int64.Type}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type3", each true),
				    #"Added Conditional Column" = Table.AddColumn(#"Filtered Rows", "Loyalty_Score2", each if [Loyalty_Level] = "Platinum" then 4 else if [Loyalty_Level] = "Gold" then 3 else if [Loyalty_Level] = "Silver" then 2 else 1),
				    #"Renamed Columns1" = Table.RenameColumns(#"Added Conditional Column",{{"Loyalty_Score2", "Loyalty_Score"}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Renamed Columns1",{"Customer_ID", "First_Name", "Last_Name", "Segment", "Email", "Join_Date", "Join_Year ", "Loyalty_Level", "Loyalty_Score"}),
				    #"Merged Columns" = Table.CombineColumns(#"Reordered Columns",{"First_Name", "Last_Name"},Combiner.CombineTextByDelimiter(" ", QuoteStyle.None),"Customer_Name")
				in
				    #"Merged Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

