table dim_salesperson
	lineageTag: c3366492-6fd5-4c58-aea5-a6967de01bc4

	measure 'Selected Person' =
			
			SELECTEDVALUE(
			    dim_salesperson[Sales_Person],
			    "All Sales Persons"
			)
			
			-- Shows the drilled salesperson's name
		displayFolder: Dynamic profile labels
		lineageTag: bbcb3798-5d4d-44ac-b2f7-ed203cafb565

	measure 'Selected Team' =
			
			SELECTEDVALUE(
			    dim_salesperson[Team],
			    "All Teams"
			)
			
			
			-- Shows the team of the selected person
		displayFolder: Dynamic profile labels
		lineageTag: d84a2c7f-2a91-4835-aef6-1abd0cbc635e

	measure 'Selected Location' =
			
			SELECTEDVALUE(
			    dim_salesperson[Location],
			    "Multiple Locations"
			)
			
			
			-- Shows location
		displayFolder: Dynamic profile labels
		lineageTag: 1803d6b7-19ff-47ff-9b03-4e37b6ffc31d

	measure 'Target Achievement %' =
			
			DIVIDE(
			    [Total Sales],
			    [Total Target],
			    0
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Dynamic profile labels
		lineageTag: 55fbb142-4f5f-4c25-ab2e-581a88d76d61

	measure 'Achievement Variance' =
			
			VAR Gap = [Sales Variance]
			RETURN
			IF(
			    Gap >= 0,
			    "+" & FORMAT(Gap, "$#,0") & " above target",
			    FORMAT(Gap, "$#,0") & " below target"
			)
		displayFolder: Dynamic profile labels
		lineageTag: bb347d82-6872-4040-adfe-6b75cd5b7eb3

	measure Measure
		displayFolder: Dynamic profile labels
		lineageTag: 05a6045f-3a79-4502-b9fa-7c48954b077e

		annotation 43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c = True

	measure 'Gauge Max' =
			
			CALCULATE(
			    SUM(fact_targets[Target_Amount]),
			    ALLEXCEPT(fact_targets, dim_salesperson[Sales_Person])
			) * 1.2
			
			 -- 20% headroom so gauge doesn't cap out
		displayFolder: Dynamic profile labels
		lineageTag: 88695f1d-5ecd-4a69-b224-37fa5e05c281

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SP_ID
		dataType: string
		lineageTag: 8dde748b-3e30-4743-9b80-58aa5ad056b5
		summarizeBy: none
		sourceColumn: SP_ID

		annotation SummarizationSetBy = Automatic

	column Sales_Person
		dataType: string
		lineageTag: 73eccec5-cbc9-4c66-abbb-27996e1415f1
		summarizeBy: none
		sourceColumn: Sales_Person

		annotation SummarizationSetBy = Automatic

	column Team
		dataType: string
		lineageTag: c7c01140-bbd0-43e9-896d-67ba814a9b92
		summarizeBy: none
		sourceColumn: Team

		annotation SummarizationSetBy = Automatic

	column Location
		dataType: string
		lineageTag: 36bcecca-59f9-4076-9db8-3a4ccaa4f7b5
		summarizeBy: none
		sourceColumn: Location

		annotation SummarizationSetBy = Automatic

	column Manager
		dataType: string
		lineageTag: 9d78b57c-a973-490c-bb52-1d92d997a068
		summarizeBy: none
		sourceColumn: Manager

		annotation SummarizationSetBy = Automatic

	column Region_Group
		dataType: string
		lineageTag: f609fa1f-0ce5-495d-8235-2015076288fe
		summarizeBy: none
		sourceColumn: Region_Group

		annotation SummarizationSetBy = Automatic

	partition dim_salesperson = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\anike\Documents\GitHub\Data Sets\Chocolate Sales Report\dim_people.csv"),[Delimiter=",", Columns=6, QuoteStyle=QuoteStyle.None]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"SP_ID", type text}, {"Sales_Person", type text}, {"Team", type text}, {"Location", type text}, {"Manager", type text}, {"Region_Group", type text}})
				in
				    #"Changed Type1"

	changedProperty = Name

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

